# Generated by Django 3.1.7 on 2021-03-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(blank=True, default='', null=True, upload_to='info_data/Blog_Posts')),
                ('Img', models.ImageField(blank=True, default='', null=True, upload_to='info_data/Blog_Posts_Images')),
                ('Category', models.CharField(choices=[('CAR_NEWS', 'CAR_NEWS'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('GEDGETS', 'GEDGETS'), ('TRAVEL', 'TRAVEL'), ('WORLDWIDE', 'WORLDWIDE')], max_length=500)),
                ('Title', models.CharField(max_length=1000)),
                ('Date', models.DateField(auto_now=True)),
                ('Author', models.CharField(max_length=100)),
                ('intro', models.TextField(blank=True, default='', null=True)),
                ('Content', models.TextField(blank=True, null=True)),
                ('Published', models.BooleanField(default=True)),
                ('Aside_Show', models.BooleanField(default=True)),
                ('Show_In_Navigation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('Short_Summery', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funny_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.FileField(upload_to='info_data/Funny_Img')),
                ('Date', models.DateField(auto_now=True)),
                ('Published', models.BooleanField(default=True)),
                ('Aside_Show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave_a_Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Viral_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to='info_data/Viral_Videos')),
                ('Thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='info_data/Viral_Videos_thumbnail')),
                ('Date', models.DateField(auto_now=True)),
                ('Author', models.CharField(max_length=200)),
                ('Published', models.BooleanField(default=True)),
                ('Aside_Show', models.BooleanField(default=False)),
            ],
        ),
    ]
