# Generated by Django 3.1.7 on 2021-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_a_reply',
            name='comment',
            field=models.CharField(max_length=300),
        ),
    ]
