# Generated by Django 3.1.7 on 2021-03-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0003_auto_20210319_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='slug',
        ),
    ]
