# Generated by Django 3.1.7 on 2021-03-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0005_auto_20210319_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='Video',
        ),
    ]
