# Generated by Django 3.1.7 on 2021-04-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0006_remove_blog_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='Category',
            field=models.CharField(choices=[('CAR_NEWS', 'CAR_NEWS'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('GEDGETS', 'GEDGETS'), ('TRAVEL', 'TRAVEL'), ('WORLDWIDE', 'WORLDWIDE')], default='', max_length=500),
        ),
        migrations.AlterModelTable(
            name='blog_post',
            table='news_data_Post',
        ),
    ]
