# Generated by Django 3.1.7 on 2021-04-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0007_auto_20210409_1032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog_post',
            table='info_data_Blog_Post',
        ),
    ]
