# Generated by Django 3.1.7 on 2021-04-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0008_auto_20210409_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
