# Generated by Django 3.1.7 on 2021-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0009_blog_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='hindi_title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
